server:
  port: 8080

spring:
  application:
    name: inventory
  r2dbc:
    url: r2dbc:postgresql://neondb_owner:c4VYelUF8jLm@ep-twilight-feather-a5ei3hpz.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: c4VYelUF8jLm
    show-sql: true
