apiVersion: v1
kind: Namespace
metadata:
  name: person

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-person-be
  namespace: person
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-person-be
  template:
    metadata:
      labels:
        app: ms-person-be
    spec:
      containers:
      - name: ms-person-be
        image: juan321/ms_person_be:latest  # Asegúrate de que 'latest' esté correctamente escrito
---
apiVersion: v1
kind: Service
metadata:
  name: ms-person-be
  namespace: person
spec:
  type: NodePort
  ports:
  - port: 30002
    targetPort: 8081
    nodePort: 30002
  selector:
    app: ms-person-be
