apiVersion: v1
kind: Namespace
metadata:
  name: product

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-product-be
  namespace: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-product-be
  template:
    metadata:
      labels:
        app: ms-product-be
    spec:
      containers:
      - name: ms-product-be
        image: juan321/ms_product_be:latest  # Asegúrate de que 'latest' esté correctamente escrito
---
apiVersion: v1
kind: Service
metadata:
  name: ms-product-be
  namespace: product
spec:
  type: NodePort
  ports:
  - port: 30001
    targetPort: 8082
    nodePort: 30001
  selector:
    app: ms-product-be
